# Generated by Django 5.2.6 on 2025-10-16 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_remove_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product')),
            ],
        ),
    ]
