# Generated by Django 5.2.6 on 2025-10-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
