# Generated by Django 5.2.6 on 2025-10-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
