# Generated by Django 5.2.6 on 2025-10-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_stocktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
