# Generated by Django 5.2.6 on 2025-10-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_date_modified'),
        ('products', '0005_stocktransaction'),
    ]

    operations = [
    ]
