# Generated by Django 5.2.6 on 2025-11-05 12:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_20251025_2225'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
