# Generated by Django 5.2.7 on 2025-11-02 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merge_20251025_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
