# Generated by Django 5.2.7 on 2025-11-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_supplier_alter_stocktransaction_date'),
        ('products', '0007_alter_stocktransaction_date'),
    ]

    operations = [
    ]
