# Generated by Django 5.2.7 on 2025-11-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_supplier'),
        ('suppliers', '0002_supplier_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier'),
            preserve_default=False,
        ),
    ]
