# Generated by Django 5.2.7 on 2025-11-25 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_stocktransaction_updated_at_alter_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_percentage', models.PositiveIntegerField(default=20)),
                ('medium_percentage', models.PositiveIntegerField(default=50)),
            ],
            options={
                'verbose_name': 'Inventory Setting',
                'verbose_name_plural': 'Inventory Settings',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='is_tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='low_threshold',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='product',
            name='max_stock_recorded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='medium_threshold',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
