# Generated by Django 5.2.7 on 2025-11-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_inventorysettings_product_is_tracked_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
