# Generated by Django 5.2.7 on 2025-12-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_delete_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='updated_at',
        ),
    ]
