# Generated by Django 5.2.6 on 2025-10-19 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_product_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_qty', models.PositiveIntegerField()),
                ('total', models.FloatField()),
                ('sales_type', models.CharField(choices=[('cash', 'CASH'), ('credit', 'CREDIT')], max_length=20)),
                ('sales_date', models.DateTimeField(auto_now_add=True)),
                ('product_sold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='products.product')),
            ],
        ),
    ]
