# Generated by Django 5.2.6 on 2025-11-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_sold_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
