# Generated by Django 5.2.7 on 2025-11-02 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_stocktransaction_date'),
        ('sales', '0002_sale_sold_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_sold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='products.product'),
        ),
    ]
