# Generated by Django 5.2.7 on 2025-11-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_product_qty_alter_sale_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sales_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
