# Generated by Django 5.2.7 on 2025-11-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_sale_sales_date'),
        ('sales', '0004_sale_amount_paid_sale_balance_sale_customer_contact_and_more'),
    ]

    operations = [
    ]
