# Generated by Django 5.2.7 on 2025-11-30 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_delete_supplier'),
        ('sales', '0006_alter_sale_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product_sold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='products.product'),
        ),
    ]
