# Generated by Django 5.2.7 on 2025-11-02 11:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_alter_sale_product_qty_alter_sale_product_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('creditor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('credit_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid')], default='unpaid', max_length=10)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('settled_date', models.DateField(blank=True, null=True)),
                ('original_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_record', to='sales.sale')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='credit.creditor')),
            ],
        ),
    ]
